import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export interface ReportData {
  userName: string;
  reportDate: string;
  overallImprovement: string;
  trainingDays: number;
  achievements: number;
  bestScore: string;
  weeklyProgress: {
    memory: string;
    attention: string;
    executive: string;
    processing: string;
  };
}

export const generatePDFReport = async (data: ReportData) => {
  const pdf = new jsPDF();
  
  // Header
  pdf.setFontSize(24);
  pdf.setTextColor(59, 130, 246); // primary color
  pdf.text('Cognitive Training Report', 20, 30);
  
  // User info
  pdf.setFontSize(12);
  pdf.setTextColor(0, 0, 0);
  pdf.text(`Generated for: ${data.userName}`, 20, 50);
  pdf.text(`Report Date: ${data.reportDate}`, 20, 60);
  
  // Key Metrics Section
  pdf.setFontSize(16);
  pdf.setTextColor(34, 197, 94); // success color
  pdf.text('Key Performance Metrics', 20, 80);
  
  pdf.setFontSize(12);
  pdf.setTextColor(0, 0, 0);
  pdf.text(`Overall Improvement: ${data.overallImprovement}`, 30, 100);
  pdf.text(`Training Days This Month: ${data.trainingDays}`, 30, 110);
  pdf.text(`Achievements Earned: ${data.achievements}`, 30, 120);
  pdf.text(`Best Score: ${data.bestScore}`, 30, 130);
  
  // Weekly Progress Section
  pdf.setFontSize(16);
  pdf.setTextColor(168, 85, 247); // accent color
  pdf.text('Weekly Progress Breakdown', 20, 150);
  
  pdf.setFontSize(12);
  pdf.setTextColor(0, 0, 0);
  pdf.text(`Memory Games: ${data.weeklyProgress.memory}`, 30, 170);
  pdf.text(`Attention Training: ${data.weeklyProgress.attention}`, 30, 180);
  pdf.text(`Executive Function: ${data.weeklyProgress.executive}`, 30, 190);
  pdf.text(`Processing Speed: ${data.weeklyProgress.processing}`, 30, 200);
  
  // Recommendations Section
  pdf.setFontSize(16);
  pdf.setTextColor(245, 158, 11); // warning color
  pdf.text('Recommendations', 20, 220);
  
  pdf.setFontSize(10);
  pdf.setTextColor(0, 0, 0);
  const recommendations = [
    '• Continue with your current training schedule',
    '• Focus on areas showing slower improvement',
    '• Try new game variations to challenge yourself',
    '• Maintain consistent daily practice sessions'
  ];
  
  recommendations.forEach((rec, index) => {
    pdf.text(rec, 30, 240 + (index * 10));
  });
  
  // Footer
  pdf.setFontSize(8);
  pdf.setTextColor(128, 128, 128);
  pdf.text('Generated by Cognitive Training Platform', 20, 280);
  
  // Save the PDF
  pdf.save(`cognitive-training-report-${new Date().toISOString().split('T')[0]}.pdf`);
};