import { ReportData } from '../../report/types';
import { BRAND, PDFContext } from '../../report/utils';
import { getNextSteps } from '../../report/analysis';

export const renderNextSteps = (ctx: PDFContext, data: ReportData) => {
  ctx.ensureSpace(50);
  ctx.addTitle('NEXT STEPS & GOALS', 16, BRAND.purple, true);
  ctx.addSeparator();

  ctx.addText('Based on your current performance, we recommend focusing on:', 11);
  const steps = getNextSteps(data);
  steps.forEach((step) => ctx.addText(`• ${step}`, 10, 10));

  // Footer on last page
  ctx.addFooter(
    'Generated by Cognitive Training Platform | Confidential Report',
    `Report ID: CTR-${Date.now().toString(36).toUpperCase()}`
  );
};
